version: '2'

services:
  testrpc:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.testrpc
    ports:
      - "8545:8545"
    command: testrpc -h 0.0.0.0 -p 8545 -i 777

  truffle:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.truffle
    volumes:
      - ../:/app
    links:
      - testrpc
    environment:
      - RPC_HOST=testrpc
    # command: truffle watch
