FROM node:7

RUN apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get install build-essential -y

RUN mkdir -p /app
ADD . /app

WORKDIR /app/src

ENV PATH "$PATH:/app/src/node_modules/.bin"

CMD npm install && tail -f /dev/null
